AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a static website to S3 with CloudFront - with a separate downloads bucket.

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bits-training-website
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DownloadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bits-training-downloads
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: bits-training-website
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}"

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: WebsiteOACConfig
        Description: Access control for CloudFront to read from S3
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: WebsiteOrigin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
              QueryString : false
              Cookies :
                Forward: none
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

# Outputs:
#   WebsiteBucketOutput:
#     Description: Website S3 bucket
#     Value: !Ref WebsiteBucket

#   DownloadsBucketOutput:
#     Description: Downloads S3 bucket
#     Value: !Ref DownloadsBucket

#   CloudFrontURL:
#     Description: CloudFront distribution domain
#     Value: !GetAtt WebsiteDistribution.DomainName
